Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 5
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Thu Nov 11 21:36:06 2021]
rule SVM_Radial:
    input: data/ATAC_predictions_train_20_predict_80/ATAC_pred_lasso_normalized_trimmed_formatted_standardized.rds, data/sample_types.txt
    output: Classification_output/SVM_radial_normalized_trimmed.rds
    log: logs/processed_notebooks/Classification/SVM_radial_normalized_trimmed.r.ipynb
    jobid: 0
    threads: 5
    resources: mem_mb=200000, disk_mb=1000, tmpdir=/scratch/56917334, time=48:00:00

jupyter-nbconvert --log-level ERROR --execute --output /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/logs/processed_notebooks/Classification/SVM_radial_normalized_trimmed.r.ipynb --to notebook --ExecutePreprocessor.timeout=-1 /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/scripts/tmpq_bt25g_.SVM_radial.r.ipynb
trying URL 'https://cran.r-project.org/src/contrib/caret_6.0-90.tar.gz'
Content type 'application/x-gzip' length 2335088 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

ERROR: failed to lock directory ‘/home/coroperv/miniconda3/envs/ctDNA/lib/R/library’ for modifying
Try removing ‘/home/coroperv/miniconda3/envs/ctDNA/lib/R/library/00LOCK-caret’

The downloaded source packages are in
	‘/scratch/56917334/RtmpKk2JVf/downloaded_packages’
Traceback (most recent call last):
  File "/home/coroperv/miniconda3/envs/ctDNA/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 346, in start
    self.convert_notebooks()
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 518, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 483, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 412, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
library(tidyverse)
library(gbm)
install.packages("caret")
library(caret)
library(pROC)
install.packages("kernlab")
library(kernlab)
------------------

Error in library(caret): there is no package called ‘caret’
Traceback:

1. library(caret)
ERROR: Error in library(caret): there is no package called ‘caret’


[Thu Nov 11 21:36:22 2021]
Error in rule SVM_Radial:
    jobid: 0
    output: Classification_output/SVM_radial_normalized_trimmed.rds
    log: logs/processed_notebooks/Classification/SVM_radial_normalized_trimmed.r.ipynb (check log file(s) for error message)

Traceback (most recent call last):
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2460, in run_wrapper
    raise ex
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2417, in run_wrapper
    run(
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/snakefile_predict_and_classify_norm_trimmed", line 333, in __rule_SVM_Radial
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/notebook.py", line 295, in notebook
    executor.evaluate(edit=edit)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/notebook.py", line 92, in execute_script
    self._execute_cmd(cmd, fname_out=fname_out, fname=fname)
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/script.py", line 414, in _execute_cmd
    return shell(
  File "/home/coroperv/miniconda3/envs/ctDNA/lib/python3.9/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  jupyter-nbconvert --log-level ERROR --execute --output /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/logs/processed_notebooks/Classification/SVM_radial_normalized_trimmed.r.ipynb --to notebook --ExecutePreprocessor.timeout=-1 /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/scripts/tmpq_bt25g_.SVM_radial.r.ipynb' returned non-zero exit status 1.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
touch: cannot touch ‘/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/tmp.9a5u0plb/9.jobfailed’: No such file or directory
